/**
 * Database van homeopathische middelen
 * Bron: William Boericke - Materia Medica (materiamedica.info)
 * Afkortingen gebaseerd op standaard homeopathische conventies
 */

export interface RemedyInfo {
  abbr: string;        // Standaard afkorting (lowercase)
  fullName: string;    // Volledige Latijnse naam
}

export const remedyDatabase: RemedyInfo[] = [
  // A
  { abbr: 'abies-c', fullName: 'Abies Canadensis' },
  { abbr: 'abies-n', fullName: 'Abies Nigra' },
  { abbr: 'abrot', fullName: 'Abrotanum' },
  { abbr: 'abrus', fullName: 'Abrus Precatorius' },
  { abbr: 'absin', fullName: 'Absinthium' },
  { abbr: 'acet-ac', fullName: 'Aceticum Acidum' },
  { abbr: 'acon', fullName: 'Aconitum Napellus' },
  { abbr: 'act-sp', fullName: 'Actaea Spicata' },
  { abbr: 'adon', fullName: 'Adonis Vernalis' },
  { abbr: 'adlu', fullName: 'Adlumia' },
  { abbr: 'adren', fullName: 'Adrenalinum' },
  { abbr: 'aesc', fullName: 'Aesculus Hippocastanum' },
  { abbr: 'aeth', fullName: 'Aethusa Cynapium' },
  { abbr: 'aethyl-s-d', fullName: 'Aethylicum Sulphuratum Dichloratum' },
  { abbr: 'agar', fullName: 'Agaricus Muscarius' },
  { abbr: 'agn', fullName: 'Agnus Castus' },
  { abbr: 'ail', fullName: 'Ailanthus Glandulosa' },
  { abbr: 'all-c', fullName: 'Allium Cepa' },
  { abbr: 'all-s', fullName: 'Allium Sativum' },
  { abbr: 'aloe', fullName: 'Aloe Socotrina' },
  { abbr: 'alum', fullName: 'Alumina' },
  { abbr: 'alum-p', fullName: 'Alumina Phosphorica' },
  { abbr: 'alum-sil', fullName: 'Alumina Silicata' },
  { abbr: 'alumn', fullName: 'Alumen' },
  { abbr: 'am-br', fullName: 'Ammonium Bromatum' },
  { abbr: 'am-c', fullName: 'Ammonium Carbonicum' },
  { abbr: 'am-caust', fullName: 'Ammonium Causticum' },
  { abbr: 'am-m', fullName: 'Ammonium Muriaticum' },
  { abbr: 'am-p', fullName: 'Ammonium Phosphoricum' },
  { abbr: 'am-val', fullName: 'Ammonium Valerianicum' },
  { abbr: 'ambr', fullName: 'Ambra Grisea' },
  { abbr: 'aml-ns', fullName: 'Amylenum Nitrosum' },
  { abbr: 'anac', fullName: 'Anacardium Orientale' },
  { abbr: 'anag', fullName: 'Anagallis Arvensis' },
  { abbr: 'anan', fullName: 'Anantherum Muricatum' },
  { abbr: 'androc', fullName: 'Androctonus' },
  { abbr: 'androg', fullName: 'Andrographis' },
  { abbr: 'ang', fullName: 'Angustura Vera' },
  { abbr: 'anh', fullName: 'Anhalonium Lewinii' },
  { abbr: 'ant-c', fullName: 'Antimonium Crudum' },
  { abbr: 'ant-t', fullName: 'Antimonium Tartaricum' },
  { abbr: 'anth', fullName: 'Anthracinum' },
  { abbr: 'aphis', fullName: 'Aphis Chenopodii Glauci' },
  { abbr: 'apis', fullName: 'Apis Mellifica' },
  { abbr: 'apoc', fullName: 'Apocynum Cannabinum' },
  { abbr: 'aran', fullName: 'Aranea Diadema' },
  { abbr: 'arg-met', fullName: 'Argentum Metallicum' },
  { abbr: 'arg-n', fullName: 'Argentum Nitricum' },
  { abbr: 'arn', fullName: 'Arnica Montana' },
  { abbr: 'ars', fullName: 'Arsenicum Album' },
  { abbr: 'ars-br', fullName: 'Arsenicum Bromatum' },
  { abbr: 'ars-h', fullName: 'Arsenicum Hydrogenisatum' },
  { abbr: 'ars-i', fullName: 'Arsenicum Iodatum' },
  { abbr: 'ars-met', fullName: 'Arsenicum Metallicum' },
  { abbr: 'ars-s-f', fullName: 'Arsenicum Sulphuratum Flavum' },
  { abbr: 'art-v', fullName: 'Artemisia Vulgaris' },
  { abbr: 'arum-d', fullName: 'Arum Dracontium' },
  { abbr: 'arum-t', fullName: 'Arum Triphyllum' },
  { abbr: 'arund', fullName: 'Arundo Mauritanica' },
  { abbr: 'asaf', fullName: 'Asa Foetida' },
  { abbr: 'asar', fullName: 'Asarum Europaeum' },
  { abbr: 'asc-c', fullName: 'Asclepias Cornuti' },
  { abbr: 'asc-t', fullName: 'Asclepias Tuberosa' },
  { abbr: 'aspar', fullName: 'Asparagus Officinalis' },
  { abbr: 'aster', fullName: 'Asterias Rubens' },
  { abbr: 'atis', fullName: 'Atis' },
  { abbr: 'aur', fullName: 'Aurum Metallicum' },
  { abbr: 'aur-ar', fullName: 'Aurum Arsenicicum' },
  { abbr: 'aur-i', fullName: 'Aurum Iodatum' },
  { abbr: 'aur-m', fullName: 'Aurum Muriaticum' },
  { abbr: 'aur-m-n', fullName: 'Aurum Muriaticum Natronatum' },
  { abbr: 'aur-s', fullName: 'Aurum Sulphuratum' },
  { abbr: 'aven', fullName: 'Avena Sativa' },

  // B
  { abbr: 'bac', fullName: 'Bacillinum' },
  { abbr: 'bad', fullName: 'Badiaga' },
  { abbr: 'bamb-a', fullName: 'Bambusa Arundinacea' },
  { abbr: 'bapt', fullName: 'Baptisia Tinctoria' },
  { abbr: 'bar-c', fullName: 'Baryta Carbonica' },
  { abbr: 'bar-i', fullName: 'Baryta Iodata' },
  { abbr: 'bar-m', fullName: 'Baryta Muriatica' },
  { abbr: 'bar-s', fullName: 'Baryta Sulphurica' },
  { abbr: 'bell', fullName: 'Belladonna' },
  { abbr: 'bell-p', fullName: 'Bellis Perennis' },
  { abbr: 'ben-ac', fullName: 'Benzoicum Acidum' },
  { abbr: 'benz', fullName: 'Benzolum' },
  { abbr: 'berb', fullName: 'Berberis Vulgaris' },
  { abbr: 'berb-a', fullName: 'Berberis Aquifolium' },
  { abbr: 'bism', fullName: 'Bismuthum Subnitricum' },
  { abbr: 'bomb-chr', fullName: 'Bombyx Chrysorrhea' },
  { abbr: 'borx', fullName: 'Borax Veneta' },
  { abbr: 'bov', fullName: 'Bovista Lycoperdon' },
  { abbr: 'brach', fullName: 'Brachyglottis Repens' },
  { abbr: 'brom', fullName: 'Bromium' },
  { abbr: 'bry', fullName: 'Bryonia Alba' },
  { abbr: 'bufo', fullName: 'Bufo Rana' },

  // C
  { abbr: 'cact', fullName: 'Cactus Grandiflorus' },
  { abbr: 'cadm-s', fullName: 'Cadmium Sulphuratum' },
  { abbr: 'caj', fullName: 'Cajuputum' },
  { abbr: 'calad', fullName: 'Caladium Seguinum' },
  { abbr: 'calc', fullName: 'Calcarea Carbonica' },
  { abbr: 'calc-ar', fullName: 'Calcarea Arsenicosa' },
  { abbr: 'calc-f', fullName: 'Calcarea Fluorica' },
  { abbr: 'calc-i', fullName: 'Calcarea Iodata' },
  { abbr: 'calc-p', fullName: 'Calcarea Phosphorica' },
  { abbr: 'calc-s', fullName: 'Calcarea Sulphurica' },
  { abbr: 'calc-sil', fullName: 'Calcarea Silicata' },
  { abbr: 'calen', fullName: 'Calendula Officinalis' },
  { abbr: 'camph', fullName: 'Camphora' },
  { abbr: 'cann-i', fullName: 'Cannabis Indica' },
  { abbr: 'cann-s', fullName: 'Cannabis Sativa' },
  { abbr: 'canth', fullName: 'Cantharis Vesicatoria' },
  { abbr: 'caps', fullName: 'Capsicum Annuum' },
  { abbr: 'carb-ac', fullName: 'Carbolicum Acidum' },
  { abbr: 'carb-an', fullName: 'Carbo Animalis' },
  { abbr: 'carb-v', fullName: 'Carbo Vegetabilis' },
  { abbr: 'carbn-o', fullName: 'Carboneum Oxygenisatum' },
  { abbr: 'carbn-s', fullName: 'Carboneum Sulphuratum' },
  { abbr: 'carc', fullName: 'Carcinosinum' },
  { abbr: 'card-m', fullName: 'Carduus Marianus' },
  { abbr: 'castm', fullName: 'Castoreum' },
  { abbr: 'caul', fullName: 'Caulophyllum Thalictroides' },
  { abbr: 'caust', fullName: 'Causticum' },
  { abbr: 'cedr', fullName: 'Cedron' },
  { abbr: 'cench', fullName: 'Cenchris Contortrix' },
  { abbr: 'cham', fullName: 'Chamomilla' },
  { abbr: 'chel', fullName: 'Chelidonium Majus' },
  { abbr: 'chin', fullName: 'China Officinalis' },
  { abbr: 'chinin-ar', fullName: 'Chininum Arsenicosum' },
  { abbr: 'chinin-s', fullName: 'Chininum Sulphuricum' },
  { abbr: 'chlol', fullName: 'Chloralum' },
  { abbr: 'chlor', fullName: 'Chlorum' },
  { abbr: 'choc', fullName: 'Chocolate' },
  { abbr: 'cic', fullName: 'Cicuta Virosa' },
  { abbr: 'cimic', fullName: 'Cimicifuga Racemosa' },
  { abbr: 'cimx', fullName: 'Cimex Lectularius' },
  { abbr: 'cina', fullName: 'Cina Artemisia' },
  { abbr: 'cinnb', fullName: 'Cinnabaris' },
  { abbr: 'cist', fullName: 'Cistus Canadensis' },
  { abbr: 'clem', fullName: 'Clematis Erecta' },
  { abbr: 'cob', fullName: 'Cobaltum Metallicum' },
  { abbr: 'coc-c', fullName: 'Coca Erythroxylon' },
  { abbr: 'coca', fullName: 'Coca' },
  { abbr: 'cocc', fullName: 'Cocculus Indicus' },
  { abbr: 'coch', fullName: 'Cochlearia Armoracia' },
  { abbr: 'cod', fullName: 'Codeinum' },
  { abbr: 'coff', fullName: 'Coffea Cruda' },
  { abbr: 'colch', fullName: 'Colchicum Autumnale' },
  { abbr: 'coloc', fullName: 'Colocynthis' },
  { abbr: 'com', fullName: 'Comocladia Dentata' },
  { abbr: 'con', fullName: 'Conium Maculatum' },
  { abbr: 'cop', fullName: 'Copaiva Officinalis' },
  { abbr: 'corn', fullName: 'Cornus Circinata' },
  { abbr: 'cortiso', fullName: 'Cortisonum' },
  { abbr: 'crat', fullName: 'Crataegus Oxyacantha' },
  { abbr: 'croc', fullName: 'Crocus Sativus' },
  { abbr: 'crot-c', fullName: 'Crotalus Cascavella' },
  { abbr: 'crot-h', fullName: 'Crotalus Horridus' },
  { abbr: 'crot-t', fullName: 'Croton Tiglium' },
  { abbr: 'cub', fullName: 'Cubeba Officinalis' },
  { abbr: 'cupr', fullName: 'Cuprum Metallicum' },
  { abbr: 'cupr-ar', fullName: 'Cuprum Arsenicosum' },
  { abbr: 'cycl', fullName: 'Cyclamen Europaeum' },

  // D
  { abbr: 'daph', fullName: 'Daphne Indica' },
  { abbr: 'dig', fullName: 'Digitalis Purpurea' },
  { abbr: 'dios', fullName: 'Dioscorea Villosa' },
  { abbr: 'dirc', fullName: 'Dirca Palustris' },
  { abbr: 'dol', fullName: 'Dolichos Pruriens' },
  { abbr: 'dor', fullName: 'Doryphora Decemlineata' },
  { abbr: 'dros', fullName: 'Drosera Rotundifolia' },
  { abbr: 'dulc', fullName: 'Dulcamara' },

  // E
  { abbr: 'echi', fullName: 'Echinacea Angustifolia' },
  { abbr: 'elaps', fullName: 'Elaps Corallinus' },
  { abbr: 'equis-h', fullName: 'Equisetum Hyemale' },
  { abbr: 'erig', fullName: 'Erigeron Canadense' },
  { abbr: 'eucal', fullName: 'Eucalyptus Globulus' },
  { abbr: 'eup-per', fullName: 'Eupatorium Perfoliatum' },
  { abbr: 'eup-pur', fullName: 'Eupatorium Purpureum' },
  { abbr: 'euph', fullName: 'Euphorbia' },
  { abbr: 'euphr', fullName: 'Euphrasia Officinalis' },
  { abbr: 'eupi', fullName: 'Eupionum' },

  // F
  { abbr: 'fago', fullName: 'Fagopyrum Esculentum' },
  { abbr: 'ferr', fullName: 'Ferrum Metallicum' },
  { abbr: 'ferr-ar', fullName: 'Ferrum Arsenicosum' },
  { abbr: 'ferr-i', fullName: 'Ferrum Iodatum' },
  { abbr: 'ferr-p', fullName: 'Ferrum Phosphoricum' },
  { abbr: 'fl-ac', fullName: 'Fluoricum Acidum' },
  { abbr: 'form', fullName: 'Formica Rufa' },

  // G
  { abbr: 'gal-ac', fullName: 'Gallicum Acidum' },
  { abbr: 'gamb', fullName: 'Gambogia' },
  { abbr: 'gels', fullName: 'Gelsemium Sempervirens' },
  { abbr: 'gent-c', fullName: 'Gentiana Cruciata' },
  { abbr: 'gent-l', fullName: 'Gentiana Lutea' },
  { abbr: 'gink-b', fullName: 'Ginkgo Biloba' },
  { abbr: 'gins', fullName: 'Ginseng' },
  { abbr: 'glon', fullName: 'Glonoinum' },
  { abbr: 'gnaph', fullName: 'Gnaphalium Polycephalum' },
  { abbr: 'gran', fullName: 'Granatum' },
  { abbr: 'granit-m', fullName: 'Granitus Marmoreus' },
  { abbr: 'graph', fullName: 'Graphites' },
  { abbr: 'grat', fullName: 'Gratiola Officinalis' },
  { abbr: 'guaj', fullName: 'Guajacum Officinale' },
  { abbr: 'gymno', fullName: 'Gymnocladus Canadensis' },

  // H
  { abbr: 'haem', fullName: 'Haematoxylon Campechianum' },
  { abbr: 'ham', fullName: 'Hamamelis Virginiana' },
  { abbr: 'hell', fullName: 'Helleborus Niger' },
  { abbr: 'hep', fullName: 'Hepar Sulphuris' },
  { abbr: 'hipp', fullName: 'Hippomanes' },
  { abbr: 'hura', fullName: 'Hura Brasiliensis' },
  { abbr: 'hydr', fullName: 'Hydrastis Canadensis' },
  { abbr: 'hydr-ac', fullName: 'Hydrocyanicum Acidum' },
  { abbr: 'hydrc', fullName: 'Hydrocotyle Asiatica' },
  { abbr: 'hydrog', fullName: 'Hydrogenium' },
  { abbr: 'hyos', fullName: 'Hyoscyamus Niger' },
  { abbr: 'hyper', fullName: 'Hypericum Perforatum' },

  // I
  { abbr: 'iber', fullName: 'Iberis Amara' },
  { abbr: 'ign', fullName: 'Ignatia Amara' },
  { abbr: 'ind', fullName: 'Indium Metallicum' },
  { abbr: 'indg', fullName: 'Indigo Tinctoria' },
  { abbr: 'iod', fullName: 'Iodium' },
  { abbr: 'ip', fullName: 'Ipecacuanha' },
  { abbr: 'iris', fullName: 'Iris Versicolor' },

  // J
  { abbr: 'jal', fullName: 'Jalapa' },
  { abbr: 'jatr-c', fullName: 'Jatropha Curcas' },
  { abbr: 'jug-c', fullName: 'Juglans Cinerea' },

  // K
  { abbr: 'kali-ar', fullName: 'Kalium Arsenicosum' },
  { abbr: 'kali-bi', fullName: 'Kalium Bichromicum' },
  { abbr: 'kali-br', fullName: 'Kalium Bromatum' },
  { abbr: 'kali-c', fullName: 'Kalium Carbonicum' },
  { abbr: 'kali-chl', fullName: 'Kalium Chloricum' },
  { abbr: 'kali-i', fullName: 'Kalium Iodatum' },
  { abbr: 'kali-m', fullName: 'Kalium Muriaticum' },
  { abbr: 'kali-n', fullName: 'Kalium Nitricum' },
  { abbr: 'kali-p', fullName: 'Kalium Phosphoricum' },
  { abbr: 'kali-s', fullName: 'Kalium Sulphuricum' },
  { abbr: 'kali-sil', fullName: 'Kalium Silicicum' },
  { abbr: 'kalm', fullName: 'Kalmia Latifolia' },
  { abbr: 'kreos', fullName: 'Kreosotum' },

  // L
  { abbr: 'lac-ac', fullName: 'Lacticum Acidum' },
  { abbr: 'lac-c', fullName: 'Lac Caninum' },
  { abbr: 'lac-d', fullName: 'Lac Defloratum' },
  { abbr: 'lach', fullName: 'Lachesis Mutus' },
  { abbr: 'lachn', fullName: 'Lachnanthes Tinctoria' },
  { abbr: 'lact', fullName: 'Lactuca Virosa' },
  { abbr: 'lappa', fullName: 'Lappa Arctium' },
  { abbr: 'laur', fullName: 'Laurocerasus' },
  { abbr: 'led', fullName: 'Ledum Palustre' },
  { abbr: 'lil-t', fullName: 'Lilium Tigrinum' },
  { abbr: 'limest-b', fullName: 'Limestone (CalciumIte)' },
  { abbr: 'lith-c', fullName: 'Lithium Carbonicum' },
  { abbr: 'lob', fullName: 'Lobelia Inflata' },
  { abbr: 'lob-e', fullName: 'Lobelia Erinus' },
  { abbr: 'luna', fullName: 'Luna' },
  { abbr: 'lyc', fullName: 'Lycopodium Clavatum' },
  { abbr: 'lycps-v', fullName: 'Lycopus Virginicus' },
  { abbr: 'lyss', fullName: 'Lyssinum (Hydrophobinum)' },

  // M
  { abbr: 'mag-c', fullName: 'Magnesium Carbonicum' },
  { abbr: 'mag-m', fullName: 'Magnesium Muriaticum' },
  { abbr: 'mag-p', fullName: 'Magnesium Phosphoricum' },
  { abbr: 'mag-s', fullName: 'Magnesium Sulphuricum' },
  { abbr: 'manc', fullName: 'Mancinella' },
  { abbr: 'mang', fullName: 'Manganum Aceticum' },
  { abbr: 'mang-act', fullName: 'Manganum Aceticum' },
  { abbr: 'marb-w', fullName: 'Marburgium' },
  { abbr: 'med', fullName: 'Medorrhinum' },
  { abbr: 'meli', fullName: 'Melilotus Officinalis' },
  { abbr: 'meny', fullName: 'Menyanthes Trifoliata' },
  { abbr: 'meph', fullName: 'Mephitis Putorius' },
  { abbr: 'merc', fullName: 'Mercurius Solubilis' },
  { abbr: 'merc-c', fullName: 'Mercurius Corrosivus' },
  { abbr: 'merc-cy', fullName: 'Mercurius Cyanatus' },
  { abbr: 'merc-d', fullName: 'Mercurius Dulcis' },
  { abbr: 'merc-i-f', fullName: 'Mercurius Iodatus Flavus' },
  { abbr: 'merc-i-r', fullName: 'Mercurius Iodatus Ruber' },
  { abbr: 'merc-k-i', fullName: 'Mercurius Kalium Iodatum' },
  { abbr: 'merl', fullName: 'Mercurialis Perennis' },
  { abbr: 'mez', fullName: 'Mezereum' },
  { abbr: 'mill', fullName: 'Millefolium' },
  { abbr: 'morph', fullName: 'Morphinum' },
  { abbr: 'mosch', fullName: 'Moschus' },
  { abbr: 'mur-ac', fullName: 'Muriaticum Acidum' },
  { abbr: 'murx', fullName: 'Murex Purpurea' },

  // N
  { abbr: 'naja', fullName: 'Naja Tripudians' },
  { abbr: 'nat-ar', fullName: 'Natrium Arsenicosum' },
  { abbr: 'nat-c', fullName: 'Natrium Carbonicum' },
  { abbr: 'nat-m', fullName: 'Natrium Muriaticum' },
  { abbr: 'nat-n', fullName: 'Natrium Nitricum' },
  { abbr: 'nat-p', fullName: 'Natrium Phosphoricum' },
  { abbr: 'nat-s', fullName: 'Natrium Sulphuricum' },
  { abbr: 'nat-sil', fullName: 'Natrium Silicatum' },
  { abbr: 'nicc', fullName: 'Niccolum Metallicum' },
  { abbr: 'nit-ac', fullName: 'Nitricum Acidum' },
  { abbr: 'nux-m', fullName: 'Nux Moschata' },
  { abbr: 'nux-v', fullName: 'Nux Vomica' },

  // O
  { abbr: 'oena', fullName: 'Oenanthe Crocata' },
  { abbr: 'ol-an', fullName: 'Oleum Animale' },
  { abbr: 'ol-j', fullName: 'Oleum Jecoris Aselli' },
  { abbr: 'olnd', fullName: 'Oleander' },
  { abbr: 'onos', fullName: 'Onosmodium Virginianum' },
  { abbr: 'op', fullName: 'Opium' },
  { abbr: 'oreo', fullName: 'Oreodaphne Californica' },
  { abbr: 'osm', fullName: 'Osmium' },
  { abbr: 'ox-ac', fullName: 'Oxalicum Acidum' },

  // P
  { abbr: 'paeon', fullName: 'Paeonia Officinalis' },
  { abbr: 'pall', fullName: 'Palladium Metallicum' },
  { abbr: 'par', fullName: 'Paris Quadrifolia' },
  { abbr: 'pareir', fullName: 'Pareira Brava' },
  { abbr: 'petr', fullName: 'Petroleum' },
  { abbr: 'ph-ac', fullName: 'Phosphoricum Acidum' },
  { abbr: 'phel', fullName: 'Phellandrium Aquaticum' },
  { abbr: 'phos', fullName: 'Phosphorus' },
  { abbr: 'phys', fullName: 'Physostigma Venenosum' },
  { abbr: 'phyt', fullName: 'Phytolacca Decandra' },
  { abbr: 'pic-ac', fullName: 'Picricum Acidum' },
  { abbr: 'pip-m', fullName: 'Piper Methysticum' },
  { abbr: 'plan', fullName: 'Plantago Major' },
  { abbr: 'plat', fullName: 'Platinum Metallicum' },
  { abbr: 'plb', fullName: 'Plumbum Metallicum' },
  { abbr: 'podo', fullName: 'Podophyllum Peltatum' },
  { abbr: 'port', fullName: 'Portulaca' },
  { abbr: 'prun', fullName: 'Prunus Spinosa' },
  { abbr: 'psil', fullName: 'Psilocybe' },
  { abbr: 'psor', fullName: 'Psorinum' },
  { abbr: 'ptel', fullName: 'Ptelea Trifoliata' },
  { abbr: 'puls', fullName: 'Pulsatilla Pratensis' },
  { abbr: 'pyrog', fullName: 'Pyrogenium' },

  // Q
  { abbr: 'quer', fullName: 'Quercus E Glandibus' },

  // R
  { abbr: 'ran-b', fullName: 'Ranunculus Bulbosus' },
  { abbr: 'ran-s', fullName: 'Ranunculus Sceleratus' },
  { abbr: 'raph', fullName: 'Raphanus Sativus' },
  { abbr: 'rat', fullName: 'Ratanhia Peruviana' },
  { abbr: 'rheum', fullName: 'Rheum Palmatum' },
  { abbr: 'rhod', fullName: 'Rhododendron Ferrugineum' },
  { abbr: 'rhus-t', fullName: 'Rhus Toxicodendron' },
  { abbr: 'rhus-v', fullName: 'Rhus Venenata' },
  { abbr: 'rob', fullName: 'Robinia Pseudacacia' },
  { abbr: 'rumx', fullName: 'Rumex Crispus' },
  { abbr: 'ruta', fullName: 'Ruta Graveolens' },

  // S
  { abbr: 'sabad', fullName: 'Sabadilla' },
  { abbr: 'sabin', fullName: 'Sabina' },
  { abbr: 'sal-ac', fullName: 'Salicylicum Acidum' },
  { abbr: 'samb', fullName: 'Sambucus Nigra' },
  { abbr: 'sang', fullName: 'Sanguinaria Canadensis' },
  { abbr: 'sanic', fullName: 'Sanicula Aqua' },
  { abbr: 'sarcol-ac', fullName: 'Sarcolacticum Acidum' },
  { abbr: 'sars', fullName: 'Sarsaparilla Officinalis' },
  { abbr: 'scroph', fullName: 'Scrophularia Nodosa' },
  { abbr: 'sec', fullName: 'Secale Cornutum' },
  { abbr: 'sel', fullName: 'Selenium Metallicum' },
  { abbr: 'senec', fullName: 'Senecio Aureus' },
  { abbr: 'seneg', fullName: 'Senega' },
  { abbr: 'sep', fullName: 'Sepia Officinalis' },
  { abbr: 'sil', fullName: 'Silicea Terra' },
  { abbr: 'sin-n', fullName: 'Sinapis Nigra' },
  { abbr: 'sol-ni', fullName: 'Solanum Nigrum' },
  { abbr: 'spig', fullName: 'Spigelia Anthelmia' },
  { abbr: 'spong', fullName: 'Spongia Tosta' },
  { abbr: 'squil', fullName: 'Squilla Maritima' },
  { abbr: 'stann', fullName: 'Stannum Metallicum' },
  { abbr: 'staph', fullName: 'Staphysagria' },
  { abbr: 'stict', fullName: 'Sticta Pulmonaria' },
  { abbr: 'still', fullName: 'Stillingia Silvatica' },
  { abbr: 'stram', fullName: 'Stramonium' },
  { abbr: 'stront-c', fullName: 'Strontium Carbonicum' },
  { abbr: 'stry', fullName: 'Strychninum Purum' },
  { abbr: 'sul-ac', fullName: 'Sulphuricum Acidum' },
  { abbr: 'sul-i', fullName: 'Sulphur Iodatum' },
  { abbr: 'sulph', fullName: 'Sulphur' },
  { abbr: 'sumb', fullName: 'Sumbulus Moschatus' },
  { abbr: 'symph', fullName: 'Symphytum Officinale' },
  { abbr: 'syph', fullName: 'Syphilinum' },

  // T
  { abbr: 'tab', fullName: 'Tabacum' },
  { abbr: 'tanac', fullName: 'Tanacetum Vulgare' },
  { abbr: 'tarax', fullName: 'Taraxacum Officinale' },
  { abbr: 'tarent', fullName: 'Tarentula Hispanica' },
  { abbr: 'tell', fullName: 'Tellurium Metallicum' },
  { abbr: 'ter', fullName: 'Terebinthiniae Oleum' },
  { abbr: 'teucr', fullName: 'Teucrium Marum Verum' },
  { abbr: 'thal', fullName: 'Thallium Metallicum' },
  { abbr: 'thea', fullName: 'Thea Chinensis' },
  { abbr: 'ther', fullName: 'Theridion Curassavicum' },
  { abbr: 'thuj', fullName: 'Thuja Occidentalis' },
  { abbr: 'til', fullName: 'Tilia Europaea' },
  { abbr: 'tub', fullName: 'Tuberculinum' },
  { abbr: 'tub-r', fullName: 'Tuberculinum Residuum' },

  // U
  { abbr: 'upa', fullName: 'Upas Tieute' },
  { abbr: 'urt-u', fullName: 'Urtica Urens' },
  { abbr: 'ust', fullName: 'Ustilago Maydis' },
  { abbr: 'uva', fullName: 'Uva Ursi' },

  // V
  { abbr: 'valer', fullName: 'Valeriana Officinalis' },
  { abbr: 'verat', fullName: 'Veratrum Album' },
  { abbr: 'verat-v', fullName: 'Veratrum Viride' },
  { abbr: 'verb', fullName: 'Verbascum Thapsus' },
  { abbr: 'vesp', fullName: 'Vespa Crabro' },
  { abbr: 'vib', fullName: 'Viburnum Opulus' },
  { abbr: 'vinc', fullName: 'Vinca Minor' },
  { abbr: 'viol-o', fullName: 'Viola Odorata' },
  { abbr: 'viol-t', fullName: 'Viola Tricolor' },
  { abbr: 'vip', fullName: 'Vipera Berus' },
  { abbr: 'visc', fullName: 'Viscum Album' },

  // W
  { abbr: 'wyeth', fullName: 'Wyethia Helenoides' },

  // X
  { abbr: 'x-ray', fullName: 'X-Ray' },
  { abbr: 'xan', fullName: 'Xanthoxylum Fraxineum' },

  // Y
  { abbr: 'yohim', fullName: 'Yohimbinum' },

  // Z
  { abbr: 'zinc', fullName: 'Zincum Metallicum' },
  { abbr: 'zinc-p', fullName: 'Zincum Phosphoricum' },
  { abbr: 'zinc-val', fullName: 'Zincum Valerianicum' },
  { abbr: 'zing', fullName: 'Zingiber Officinale' },
  { abbr: 'ziz', fullName: 'Zizia Aurea' },
];

// Index voor snelle lookup op afkorting
const abbrIndex = new Map<string, RemedyInfo>();
for (const r of remedyDatabase) {
  abbrIndex.set(r.abbr, r);
}

/**
 * Zoek een middel op basis van afkorting
 */
export function lookupRemedy(abbr: string): RemedyInfo | undefined {
  return abbrIndex.get(abbr.toLowerCase().trim());
}

/**
 * Zoek middelen op naam (afkorting of volledige naam)
 */
export function searchRemedies(query: string): RemedyInfo[] {
  const term = query.toLowerCase().trim();
  if (!term) return [];

  return remedyDatabase.filter(r =>
    r.abbr.includes(term) ||
    r.fullName.toLowerCase().includes(term)
  );
}
