import { Case, SavedRubric } from './types';
import { parseRemedies } from './parseRemedies';

interface RubricData {
  id: string;
  name: string;
  remedyString: string;
}

const sampleRubricData: RubricData[] = [
  { id: 'r1', name: 'Generals - Sun - exposure to sun', remedyString: 'Acon, adlu, aeth, Agar, aloe, aml-ns, anh, ANT-C, Arg-met, arn, Ars, Bar-c, BELL, brom, Bry, cact, cadm-s, calc, calc-f, Camph, Carb-v, carc, cina, clem, cocc, crot-h, Euphr, fago, Gels, GLON, graph, ign, iod, ip, Kalm, LACH, lappa, Lyss, mag-m, med, merc, merc-c, mur-ac, NAT-C, NAT-M, nat-n, Nux-v, Op, port, prun, psil, Psor, PULS, Sel, stann, stram, sul-i, sulph, syph, ther, thuj, uva, Valer, verat-v, Zinc' },
  { id: 'r2', name: 'Extremities - coldness - foot', remedyString: 'abrot, absin, acet-ac, Acon, agar, aloe, alum, alum-p, alum-sil, alumn, Am-br, Am-c, am-m, amr, Anac, androc, ang, ANT-C, ANT-T, anth, aphis, apis, APOC, Arg-n, Arn, ARS, ARS-I, ars-s-f, asaf, Asar, asc-t, AUR, aur-ar, aur-i, aur-s, bamb-a, bapt, Bar-c, bar-i, bar-m, bar-s, BELL, ben-ac, berb, Bov, brach, BROM, bry, bufo, Cact, calad, CALC, Calc-i, calc-p, calc-s, calc-sil, Camph, cann-i, cann-s, Canth, Caps, Carb-ac, Carb-v, carbn-o, CARBN-S, Caul, CAUST, cedr, Cham, Chel, CHIN, Chinin-ar, choc, cic, cimic, Cimx, cina, cinnb, Cist, Cocc, coff, Colch, Con, crat, Crot-c, crot-h, Crot-t, CUPR, cupr-ar, daph, DIG, dor, DROS, elaps, eup-per, fago, FERR, ferr-ar, FERR-I, ferr-p, fl-ac, form, Gels, Glon, GRAPH, Hell, Hep, hipp, hura, hydrc, Hydrog, hyos, hyper, iber, ign, ind, IOD, IP, iris, KALI-AR, kali-bi, KALI-C, KALI-M, KALI-P, KALI-S, kali-sil, KREOS, lac-ac, lac-d, LACH, lact, laur, led, lil-t, limest-b, LYC, Lycps-v, mag-c, mag-m, mag-s, manc, Mang, Med, MENY, MERC, Merc-c, mez, morph, Mur-ac, naja, Nat-ar, NAT-C, NAT-M, Nat-p, Nat-s, NIT-AC, Nux-m, Nux-v, oena, ol-an, ol-j, olnd, op, Ox-ac, pall, PAR, PETR, PH-AC, PHOS, Phyt, Pic-ac, pip-m, plan, plat, Plb, Podo, Psor, ptel, PULS, raph, RHOD, Rhus-t, rob, rumx, ruta, SABAD, Sabin, Samb, sang, Sars, Sec, SEP, SIL, spong, SQUIL, Stann, staph, STRAM, stront-c, stry, sul-ac, SULPH, sumb, tab, Tarent, tell, THUJ, tub, Verat, Verat-v, verb, vesp, Zinc' },
  { id: 'r3', name: 'Eyes - discharge - watery', remedyString: 'acon, cortiso, dulc, euphr' },
  { id: 'r4', name: 'Eyes - discolorations - red - lids', remedyString: 'Acon, ANT-C, apis, Arg-met, ARG-N, Ars, ars-i, ars-s-f, Aur, aur-s, bamb-a, bar-c, bar-i, bar-m, Bell, berb, bomb-chr, Bry, Calc, calc-i, calc-sil, cann-s, Carbn-s, Caust, cham, chel, Chinin-s, cinnb, Cocc, colch, com, Crot-t, cupr, elaps, EUPHR, Ferr, Ferr-ar, ferr-i, ferr-p, GELS, gink-b, granit-m, Graph, Hep, iod, Kali-ar, kali-bi, Kali-c, KALI-I, Lac-d, LYC, mag-m, MERC, Merc-i-f, Mur-ac, Nat-m, nicc, nux-v, PETR, plb, podo, psor, Puls, ran-b, rhod, Rhus-t, rhus-v, sabad, sanic, Sep, sil, sul-i, Sulph, TELL, teucr, upa, vinc, zinc, zinc-p' },
  { id: 'r5', name: 'Eye - Photophobia', remedyString: 'ACON, aeth, aethyl-s-d, agar, Agn, Ail, All-c, Alum, alum-p, alum-sil, am-c, am-m, anac, Anan, ant-c, Ant-t, apis, ARG-N, Arn, ARS, Arum-t, arund, Asar, asc-t, atis, Aur, aur-ar, Aur-m, aur-s, bapt, BAR-C, bar-i, Bar-m, bar-s, BELL, berb, borx, brom, Bry, bufo, cact, CALC, Calc-p, calc-s, calc-sil, camph, cann-i, carb-ac, CARBN-S, carc, castm, Caust, cedr, cere-b, Cham, Chel, CHIN, Chinin-ar, Chinin-s, chlol, Cic, cimic, cina, cinnb, Clem, Coff, coloc, CON, Croc, Crot-h, Crot-t, Dig, dirc, dros, elaps, Eup-per, EUPHR, ferr, ferr-i, gal-ac, gamb, Gels, Glon, GRAPH, Hell, Hep, hydro-v, Hyos, Ign, ip, Kali-ar, Kali-bi, Kali-c, kali-i, kali-m, Kali-n, Kali-p, kali-s, Lac-ac, LAC-C, Lac-d, Lach, Led, Lil-t, Lith-c, luna, LYC, lyss, mag-m, Mag-p, mag-s, mang, marb-w, med, MERC, Merc-c, Merc-i-f, Merl, mosch, mur-ac, Nat-ar, Nat-c, NAT-M, nat-p, NAT-S, nicc, nit-ac, nux-m, NUX-V, OP, petr, ph-ac, Phos, phys, Phyt, psil, Psor, ptel, Puls, ran-b, RHUS-T, atis-r, Sanic, sarr, sec, seneg, Sep, Sil, sol-ni, Spig, staph, Stram, sul-ac, SULPH, Sumb, syph, Tab, tarax, Tarent, ther, Tub, Verat, Zinc, ziz' },
  { id: 'r6', name: 'Nose - Discharge - watery', remedyString: 'abrot, Acon, aesc, Agar, ail, ALL-C, aloe, alum, alum-sil, am-br, am-c, am-caust, am-m, anag, androg, ant-c, ant-t, anth, aphis, apis, arg-met, ARS, Ars-i, ARUM-T, arund, asar, aur-ar, Aur-m, bad, bamb-a, bell, berb, bov, Brom, Bry, bufo, cham, Calc, calc-i, calc-p, calc-s, calc-sil, carb-an, Carb-v, carbn-s, castm, cench, CHAM, chel, CHIN, chinin-ar, chlor, cinnb, clem, cob, coc-c, coca, coff, colch, coloc, con, cortiso, cub, cupr, cupr-ar, Cycl, dios, dros, Dulc, elaps, eup-pur, euph, EUPHR, ferr, ferr-ar, Ferr-i, Fl-ac, gels, granit-m, GRAPH, guaj, ham, hep, Hydr, Hydrog, ign, ind, IOD, Kali-bi, Kali-i, kali-n, Kali-p, kreos, lac-c, lach, lil-t, limest-b, luna, lyss, mag-c, mag-m, mag-s, marb-w, meny, MERC, mez, mur-ac, naja, NAT-AR, nat-c, Nat-m, nat-s, NIT-AC, NUX-V, osm, ox-ac, pall, par, petr, phos, Phyt, PLAN, plb, puls, ran-s, rumx, Sabad, Sang, Seneg, sep, Sil, sin-n, spig, squil, staph, sul-ac, Sulph, TELL, ter, teucr, thuj, zinc' },
  { id: 'r7', name: 'Nose - sneezing - frequent', remedyString: 'acon, agar, All-c, alum, alum-p, alum-sil, am-c, AM-M, ambr, anac, arg-met, arn, ARS, asaf, aspar, Aur, bar-c, bar-m, Bell, Brom, Bry, calc, carb-an, CARB-V, CARBN-S, castm, Caust, chinin-s, cic, cist, COC-C, con, con-r, cortiso, crot-h, cupr, Cycl, dig, Dros, Dulc, euph, gink-b, gins, graph, gymno, Hep, hydrog, hyos, kali-ar, Kali-c, kali-i, kali-n, kali-p, kali-sil, kalm, Kreos, lact, laur, lil-t, Lyc, mag-c, mag-m, mag-s, mang, MERC, mez, mosch, mur-ac, nat-ar, Nat-c, nat-m, Nit-ac, nux-m, NUX-V, petr, Phos, Plan, prun, PULS, ran-s, rhus-t, ruta, Sang, scor, sep, Sil, spig, Squil, stann, staph, Stict, stront-c, SULPH, ther, verat, Zinc' },
  { id: 'r8', name: 'Nose - sneezing - violent', remedyString: 'acon, all-c, am-c, anag, aphis, arg-met, Ars, ars-h, asaf, asar, aspar, Bar-c, brom, Bry, calad, canth, caps, carb-v, cench, chin, chlor, cina, Cist, Coc-c, Con, Croc, Crot-h, Dig, Fl-ac, Gamb, gels, gymno, ictod, Ind, indg, Ip, kali-ar, Kali-c, Kali-i, kali-p, kali-sil, laur, lyc, mag-c, merc, mosch, Nat-ar, Nat-c, nat-m, nicc, nit-ac, nux-v, olnd, puls, rhus-t, rumx, sabad, seneg, sil, Squil, sulph, ther, Thuj, verat' },
  { id: 'r9', name: 'Generals - Night agg', remedyString: 'abel, abrot, acet-ac, ACON, agar, agn, agre, aloe, alum, ALUM-P, alum-sil, alumn, Am-br, am-c, Am-m, ambr, Ammc, anac, androc, ang, Ant-c, Ant-t, apis, apoc, Aral, aran, arg-met, ARG-N, arist-cl, ARN, ARS, ARS-I, ARS-S-F, Asaf, asar, aster, Aur, aur-ar, aur-i, aur-m, AUR-S, bac, Bar-c, bar-i, Bar-m, Bar-s, Bell, benz-ac, berb-a, bism, borx, Bov, Brom, Bry, bufo, buni-o, but-ac, cact, caj, calad, CALC, calc-ar, CALC-I, CALC-P, CALC-S, CALC-SIL, Camph, Cann-i, Cann-s, Canth, Caps, carb-ac, CARB-AN, Carb-v, CARBN-S, Caust, cedr, Cench, CHAM, Chel, CHIN, chinin-ar, chion, cic, cimic, cina, CINNB, clem, coc-c, Cocc, Cod, COFF, COLCH, Coloc, com, CON, convo-s, cory, Croc, crot-c, Crot-h, crot-t, Cupr, CYCL, cyt-l, Dig, dios, dol, Dros, DULC, elaps, Equis-h, erig, eucal, Euphr, FERR, FERR-AR, FERR-I, Ferr-p, Fl-ac, flav, Gamb, gink-b, GRAPH, grat, guaj, hed, Hell, HEP, hip-ac, Hydrog, HYOS, Ign, IOD, IP, iria, jal, KALI-AR, KALI-BI, Kali-br, KALI-C, KALI-I, Kali-m, kali-n, Kali-p, Kali-sil, kalm, kreos, LACH, laur, Led, LIL-T, lob, luna, Lyc, MAG-C, MAG-M, mag-p, mand, MANG, meny, meph, MERC, Merc-c, Merc-i-f, MERC-K-I, Mez, moly-met, mosch, Mur-ac, Nat-ar, Nat-c, Nat-m, Nat-p, Nat-s, Nat-sil, nep, NIT-AC, Nux-m, Nux-v, Olnd, Op, Ox-ac, par, pareir, Petr, Ph-ac, phenob, PHOS, Phyt, Pic-ac, plat, PLB, PSOR, PULS, pyrog, ran-b, ran-s, rat, rheum, Rhod, RHUS-T, rumx, ruta, Sabad, sabin, sal-ac, Samb, sang, sarcol-ac, Sars, scir, Sec, Sel, senec, seneg, SEP, sieg, SIL, sin-n, Spig, Spong, squil, Stann, Staph, stict, still, stram, STRONT-C, Sul-ac, SUL-I, SULPH, SYPH, tarax, tarent, TELL, ter, teucr, thal, thea, ther, Thuj, trios, valer, verat, verb, vib, Viol-t, vip, visc, x-ray, ZINC, ZINC-P' },
  { id: 'r10', name: 'Head - Fullness', remedyString: 'abrot, ACON, Aesc, aethyl-n, agar, ail, all-c, am-c, Am-m, ang, apis, Arg-n, arn, arum-t, asaf, Aster, aur, aur-ar, aur-s, bapt, Bell, berb, Borx, bov, Bry, CACT, Calc, Calc-p, calc-s, calc-sil, cann-i, canth, caps, carb-ac, carb-an, Carb-v, carbn-s, Card-m, Carl, castm, cench, cham, chin, Chinin-ar, chinin-s, chr-ac, cimic, Cinnb, clem, cob, coc-c, coff, Con, corn, crot-h, cupr, cupr-ar, cycl, daph, Dig, Dios, dulc, echi, elaps, Ferr, ferr-ar, ferr-p, fl-ac, form, Gels, Gent-c, gent-l, gins, GLON, gnaph, granit-m, grat, guaj, gymno, Ham, Hell, helo, hydr, Hyos, hyper, ign, ip, iris, jac-g, jug-c, kali-ar, kali-c, kali-p, kali-i, kali-s, kali-sil, kalm, kreos, lac-ac, Lac-d, LACH, lact, laur, lil-t, lyc, meli, meph, Merc, merc-i-r, mill, naja, nat-ar, nat-c, nat-m, nat-p, nat-s, Nicc, Nux-m, nux-v, onos, op, osm, Paeon, Petr, phel, Phos, phys, phyt, pic-ac, plan, Psor, puls, Ran-b, Ran-s, raph, Rhus-t, rumx, sabad, samb, Sang, Sel, senec, sep, sil, sol-ni, Spong, stram, Stry, Sul-ac, SULPH, syph, tab, tanac, tell, Ter, thuj, til, urt-u, ust, valer, verat-v, Xan, ziz' },
  { id: 'r11', name: 'Eye - heat in lids', remedyString: 'acon, benz-ac, bomb-chr, Calc, calc-p, chel, cinnb, Gels, Glon, Graph, lil-t, Med, sep, syph, upa' },
  { id: 'r12', name: 'Mind - ailments from - anger', remedyString: 'ACON, agar, alum, alum-sil, am-c, anac, anan, ant-c, Ant-t, Apis, arg-met, arg-n, arn, Ars, ars-s-f, Aur, aur-ar, Aur-m, aur-m-n, bar-c, Bell, Bry, cadm-s, calc, calc-ar, Calc-p, calc-s, calc-sil, camph, carc, caust, CHAM, chin, cimic, cina, cist, COCC, Coch, Coff, colch, COLOC, croc, cupr, ferr, ferr-p, Gels, graph, grat, hyos, IGN, iod, IP, kali-br, Kali-p, Lach, Lyc, mag-c, mag-m, manc, merc, mez, nat-ar, nat-c, Nat-m, nat-p, nat-s, NUX-V, ol-an, olnd, OP, petr, Ph-ac, Phos, PLAT, Puls, ran-b, rhus-t, samb, scroph, sec, sel, Sep, sil, stann, STAPH (4), stram, stront-c, sulph, Tarent, verat, vesp, vinc, zinc, zinc-p' },
  { id: 'r13', name: 'Head - heaviness', remedyString: 'abrom-a, acet-ac, achy-a, Acon, aesc, aeth, Agar, agn, ail, all-c, aloe, Alum, alum-p, alum-sil, am-c, Am-m, ambr, anac, anan, androc, ang, ant-t, apis, APOC, Arg-n, Arn, Ars, ars-i, arum-t, asaf, asar, asc-r, aur, aur-ar, aur-i, aur-m-n, bamb-a, bapt, bar-c, bar-i, bar-m, Bell, berb, bism, borx, bov, brom, Bry, bufo, Cact, Calc, calc-ar, calc-i, Calc-s, Camph, Cann-i, Canth, Carb-ac, Carb-an, CARB-V, CARBN-S, Card-m, castm, caust, cedr, Cham, Chel, CHIN, chinin-ar, Chinin-s, cic, cimic, cinnb, Clem, coc-c, coca, cocc, coff, Colch, coloc, Con, cop, Corn, croc, Crot-c, Crot-h, Crot-t, Cupr, cycl, desm-g, Dig, dios, Dros, Dulc, elaps, euphr, eupi, ferr, ferr-ar, ferr-i, ferr-p, fl-ac, form, Gamb, GELS, gent-c, gins, Glon, gran, graph, grat, gymno, haem, Hell, hep, hipp, hura, hydr, hydr-ac, Hydrog, Hyos, hyper, Ign, indg, iod, Ip, iris, jatr-c, kali-ar, Kali-bi, kali-c, Kali-i, kali-m, Kali-n, Kali-p, kali-s, kreos, lac-c, LACH, lachn, Lact, Laur, led, lil-t, limest-b, lob, lob-e, luna, Lyc, Mag-c, Mag-m, Mag-s, manc, Mang, mang-act, marb-w, med, Meny, meph, Merc, merc-c, merc-i-f, merc-i-r, Merl, mez, morph, mosch, MUR-AC, murx, naja, Nat-ar, Nat-c, NAT-M, Nat-p, nat-s, Nicc, NIT-AC, nux-m, NUX-V, ol-an, Olnd, onos, Op, oreo, osm, paeon, par, PETR, Ph-ac, Phel, Phos, phys, phyt, PIC-AC, pip-m, plan, plat, Plb, prun, ptel, Puls, ran-b, ran-s, rat, rheum, Rhus-t, ruta, Sabad, sang, Sars, Sec, Seneg, Sep, Sil, sol-ni, spig, squil, Stann, Staph, stram, Stront-c, Sul-ac, sul-i, SULPH, Tab, Tarax, Tarent, tell, ter, thea, ther, Thuj, til, tub, tub-r, ust, valer, verat, verat-v, verb, viol-o, Viol-t, vip, Zinc, zinc-p, zing' },
];

function makeRubric(id: string, name: string, remedyString: string) {
  return {
    id,
    name,
    remedies: parseRemedies(remedyString),
    createdAt: Date.now(),
  };
}

export function createSampleCase(): Case {
  const rubrics = sampleRubricData.map(d => makeRubric(d.id, d.name, d.remedyString));

  return {
    id: 'sample-case-1',
    name: 'Voorbeeldcasus (13 rubrieken)',
    rubrics,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}

export function createSampleLibrary(): SavedRubric[] {
  return sampleRubricData.map(d => ({
    name: d.name,
    remedyString: d.remedyString,
    remedyCount: parseRemedies(d.remedyString).length,
    lastUsed: Date.now(),
    usageCount: 1,
  }));
}
